version: "3.3"
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    stdin_open: true
    tty: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: express_app
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev
    env_file:
      - .env
    depends_on:
      - db
volumes:
  db_data:
